### PR TITLE
Cubic monotone interpolation.

### PR DESCRIPTION
**Pull request by mbostock**
- [x] tests
- [ ] documentation
- [x] decide on start and end slopes: one-sided
- [x] fix one-sided slope with h0 = 0 or h1 = 0
- [x] decide how to deal with non-monotonic data in x (h0 < 0 or h1 < 0): document it

### CODE REVIEW

**Comment by mbostock** [comment]
Test case from Wikipedia:

[screen shot 2015-11-26 at 1 33 23 pm](http://bl.ocks.org/mbostock/ed45d78bc4959809bb36)

Seems to differ a bit from Fritsch–Carlson. And actually centripetal Catmull–Rom splines look a bit better in this case while coincidentally preserving monotonicty.

**Comment by jviide** [comment]
If you happen to be looking for data that produces some overshoot then at least points ```[[0, 224], [100, 200], [107, 180], [502, 300], [580, 120], [607, 148], [900, 400]]``` seem to do the trick with ```natural``` and ```catmullRom```.

**Comment by mbostock** [comment]
Here’s your example:

screen shot 2015-11-27 at 3 33 40 pm

I agree that uniform Catmull–Rom splines don’t do very well here (red, α = 0), but centripetal does (green, α = 0.5). I also think from this example that using zero slope for the first and last point may not be the best default behavior, although it is simple…

**Comment by mbostock** [comment]
I changed the default α for Catmull–Rom splines to 0.5 in 5a21ab2feade0c6bd2db38f144a7666a475a8607. This is a better default behavior and also has the nice side-effect that curve(cardinal) and curve(catmullRom) now behave differently.

**Comment by jviide** [comment]
Yeah. The monotone ones (be it Steffen or Fritsch-Carlson) are somewhat useful for plotting smooth lines through data points where you might want to avoid overshoot but can't choose the curve parameters beforehand. They rarely provide the best looking solution though.

I'll have a look at replacing the zero slopes at boundaries with something better. For example just choosing the slope between the boundary point and its neighbor might be ok.

**Comment by mbostock** [comment]
Yes, the monotonicity guarantee is still useful for data visualization even
if centripetal Catmull–Rom is perhaps the best in the general case.

And yep, that’s what I would try for the first and last slope, too. Send me
a PR to the monotone branch if you get it working? Thanks.

**Comment by jviide** [comment]
I made the PR (and of course messed up the target branch, sigh), but here's a comparison similar to the one you made with the different boundary handling applied:

curves

**Comment by mbostock** [comment]
Nice. This looks great!

screen shot 2015-11-27 at 8 30 40 pm

I noticed some an edge case that needs testing. If two adjacent points have the same *x*-value, it has different behavior than if the two points are separated by a small ε. Here’s x₀ = x₁

screen shot 2015-11-27 at 8 33 26 pm
:

And here’s  x₁ - x₀ = 1e-6:

screen shot 2015-11-27 at 8 35 23 pm

I *think* this is just an issue with the first and last segment, though. The rest of the code seems to handle duplicate *x*-values okay. Though, it doesn’t appear to gracefully handle data that is not monotonic in *x*. But that’s probably fine to ignore for this curve, and document it as an assumption.

**Comment by mbostock** [comment]
Okay, pushed a fix in c1a9743.

**Comment by jviide** [comment]
Great, thank you!

**Pull request closed without merging**
